name: Summarize package test results
on:
  workflow_run:
    workflows: ["Dummy log generator"]
    types:
      - completed

jobs:
  summarize:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://api.github.com/repos/isc-shuliu/summarize-log-workflow/actions/runs
    steps:
      - name: Donwload log zip
        run: |
          curl -L -o logs.zip "${{ env.BASE_URL }}/${{ github.event.workflow_run.id }}/logs" -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
      - name: Unzip logs
        run: |
          unzip logs.zip -d /tmp/logs/
      - name: Summarize logs
        run: |
          ls -R /tmp/logs/

